### ISSUE TITLE
imsmanifest identifier replacement error

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-contrib-spoor#24]
For older courses that do not have _spoor.identifier set its [value](https://github.com/deltanet/adapt-contrib-spoor/blob/master/required/imsmanifest.xml#L2) is replaced with the spoor JSON object.

It would be better to update this value to the OS _manifestIdentifier value which has a shim in the framework [replace grunt task](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/config/replace.js#L70). 

This would require a migration task in the AT to move the _spoor.identifier value to _spoor._advancedSettings._manifestIdentifier.

Also see https://github.com/deltanet/adapt-contrib-spoor/issues/16

**Comment by deltanetdan** [comment]
Fixed in latest
